service: appsyncmasterclass-backend

frameworkVersion: "2"

plugins:
  - serverless-appsync-plugin

provider:
  name: aws
  runtime: nodejs12.x

package:
  exclude:
    - package.json
    - package-lock.json

custom:
  appSync:
    - ${file(serverless.appsync-api.yml)}

resources:
  Resources:
  
    Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
